" Max Claus Nunes's .vimrc
set nocompatible " be modern
filetype plugin indent on
syntax on

" source ~/.vim/filetypes.vim
source ~/.vim/plugins.vim
source ~/.vim/settings.vim
source ~/.vim/plugins-settings.vim
source ~/.vim/mappings.vim
" source ~/.vim/spelling.vim

" Source a local vimrc if it exists
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
